services:
  rhost:
    build: .
    restart: unless-stopped
    working_dir: /app
    command: ["/bin/sh", "-c", "/app/start.sh"]
    volumes:
      - ./app:/app
    ports:
      - "10001:10001"
      - "10000:10000"
