services:
  dynamic-webpages:
    image: denoland/deno:alpine
    restart: unless-stopped
    working_dir: /app
    command: ["deno", "run", "--node-modules-dir=none", "--allow-net", "--allow-read", "--allow-write=/app/logs", "--allow-env", "index.js"]
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    environment:
      - RHOST_ENDPOINT=${RHOST_ENDPOINT}
